#pragma once

#include <array>
#include <cstdint>

#include "core/Half.hpp"
#include "core/Tile.hpp"
#include "core/TileStore.hpp"

// core/Mask (PLAN.md "Phase 5 -- Stack it", step 4: "Layer masks --
// single-channel tile store, the same machinery"). PRD C4 (P0: "Layers behave
// as in Photoshop: reorder, group, opacity, blend mode, **per-layer mask**,
// visibility, lock"), PRD C3 (P0: "Layer opacity means transparency on every
// kind"), PRD C2, PRD I4; docs/document-format.md's `mask` channel on a layer
// part.
//
// --- What a layer mask is, in one sentence --------------------------------
//
// **A layer mask is per-texel opacity, and nothing else.** It multiplies the
// same coverage `Layer::opacity` multiplies, at the same point in the walk,
// after the same op stack -- so PRD C3's "opacity means transparency on every
// kind" is the sentence that governs it, made per texel. core/Composite.hpp §5
// works that out for each layer kind and proves the composition; this header
// owns the storage and the value rules.
//
// It is **not** a clipping mask. A clipping mask is a layer clipped by the
// alpha of the layer *below* (PRD C9), it stores nothing of its own, and
// PLAN.md schedules it separately as Phase 5 step 9. The two words are one
// letter apart and the features share no code.
//
// --- The tile: one f16 channel, 32 KiB ------------------------------------
//
// **Single channel at binary16**, 128*128*2 = 32 KiB per occupied tile --
// **a quarter** of core::Tile's 128 KiB and **a seventh** of
// core::PigmentTile's 224 KiB, so fully masking an RGB layer costs 1.25x its
// tiles and fully masking a Pigment layer 1.14x. Two alternatives were
// considered and both lose:
//
//  * **`uint8` (16 KiB, half again cheaper).** PLAN.md's *phase 7* line for
//    the **selection** coverage store says `r8unorm`, and that is the right
//    call there -- a selection is transient, canvas-sized and regenerated by a
//    tool. A layer mask is document data that must survive a save, and
//    docs/document-format.md puts the `mask` channel **in the layer's own EXR
//    part**, where `io::NpaintRawPart` carries exactly one `sampleTypeName`
//    for all of that part's channels. So an 8-bit in-memory mask on a HALF
//    part would be quantised on every load, and the "HALF in, HALF out, no
//    conversion" bit-exactness io/NpaintFile claims for a layer part would
//    stop being true for one of its channels. The quality difference is also
//    real and derived rather than asserted: binary16's worst absolute error
//    over [0,1] is half an ulp at the top of the range, 2^-12 = 2.441e-04,
//    against uint8's 1/510 = 1.961e-03 -- **8x** -- and a mask is exactly the
//    place a long smooth ramp gets looked at against a flat colour.
//  * **`float` (64 KiB).** Twice the cost for precision no coverage needs; the
//    working space is `rgba16float` for the same reason (DESIGN-imaging.md
//    §2).
//
// --- Absent, all-1.0 and all-0.0 are three different things ----------------
//
// This is the part that has to be got right, because getting it wrong shows up
// as a layer that has silently vanished.
//
//   **Absent** -- `Layer::mask` is `std::nullopt`. The layer has no mask.
//     Costs nothing anywhere: no allocation, no `mask` channel in the file,
//     and no arithmetic in the composite (core/Composite takes the identical
//     code path it took before this step, which is why step 1's byte-identity
//     regression boundary survives to the ulp).
//   **All 1.0** -- the mask exists and reveals everything. The *canonical*
//     form of this is an engaged store with **zero tiles**, which is what
//     `core::addLayerMask()` creates: an unallocated mask tile means 1.0, so
//     "reveal all" is free. It composites byte-identically to absent and
//     differs from it in exactly two observable ways: the layers panel says
//     `MASK`, and the file carries a `mask` channel.
//   **All 0.0** -- the mask exists and hides everything. This is *not* free:
//     it is real content, 32 KiB per tile, exactly as a painted stroke is.
//     It composites byte-identically to the layer being deleted.
//
// **An unallocated mask tile therefore means 1.0, not 0.0, and `MaskTile`'s
// own default matches it** -- the constructor fills the buffer with binary16
// 1.0 rather than leaving it zeroed. That is the one place this type departs
// from core::Tile and core::PigmentTile, whose zeroed default (transparent
// black, mass 0) is their "no content". The reason is that a mask is the
// *complement* of content: the value that means "nothing here" is the identity
// of the multiply it feeds, and for a multiply that is 1. Had the default been
// 0, `getOrCreate()` would hand back a tile that hides 16 384 texels until
// each is written, and a mask painted on one tile of a four-tile layer would
// blank the other three. That is precisely the "discovered by the user as a
// black layer" failure, and it is designed out rather than warned about.
//
// A consequence io/NpaintFile relies on: the drop-on-read rule for a mask tile
// is "every sample is exactly 1.0", the mirror of the "every sample is zero"
// rule the RGB and Pigment unpackers already apply. Same rule, different
// identity element, for the same reason -- a tile indistinguishable from an
// unallocated one must not be allocated, or a sparse document's resident cost
// would grow on every save-and-reopen.
//
// --- Out-of-range and NaN: clamped, at every boundary, and named on load ---
//
// A mask sample is a coverage, and this codebase already has exactly one rule
// for a coverage that is not in [0,1]: `core::layerCoverage()` clamps, with
// `!(v > 0)` rather than `std::max` "so a NaN lands on 0 instead of
// propagating through the whole canvas". `maskCoverageClamp()` below is that
// same expression, and using a second rule for the same quantity would be the
// kind of divergence that is only ever found by a user.
//
// So: **clamp, not refuse and not propagate.**
//
//   * Refusing is impossible where it would have to happen. There are 16 384
//     samples in a tile and the read path is a `float` return with nowhere to
//     put an error; a per-texel refusal is not a thing a compositor can have.
//   * Propagating is the one genuinely bad answer: a single NaN mask sample
//     multiplied into a premultiplied texel poisons the accumulator, and from
//     there part 0 of every save and every exported pixel.
//
// The clamp is applied on **write** (so nothing this build stores is ever out
// of range), on **read** (so nothing a *file* stored can reach the composite),
// and at **load**, where io/NpaintFile additionally rewrites the offending
// half words to their clamped value and **warns by name with a count**. That
// last part is what keeps the decision from being discovered as a black layer:
// the clamp is silent arithmetic, and a silent clamp on data the user did not
// author is exactly the thing PRD I11 exists to forbid.
//
// NaN clamping to 0 rather than to 1 deserves its own line, because the choice
// is between "the layer vanishes" and "the mask does nothing" and neither is
// pleasant. It goes to 0 because that is what `layerCoverage()` does with a
// NaN opacity -- one rule for one quantity -- and because the load-time
// warning, not the clamp target, is what makes it discoverable.
//
// --- What is deliberately not here ----------------------------------------
//
// **Nothing can paint a mask.** `sim::PaintSim` owns one dense GPU texture and
// no stroke reaches a `Layer` of any kind, so the only ways a mask gets
// content are loading a `.npaint` that has some or a test writing texels --
// the same gap core/Layer.hpp states for `pigmentTiles`, unchanged by this
// step. Mask *editing* (brush, feather, density, invert, "apply mask"),
// selection <-> mask conversion (PRD E5) and Hide All all follow the brush and
// the selection store, which are Phase 10 and Phase 7.
//
// Also not here: a mask on a **group** (this build creates no groups), a
// vector mask (PRD's deferred list, phase 13's paths), and any second mask
// slot. `Layer::mask` is one optional store, which is what PRD C4's "per-layer
// mask" names.
namespace np {

// One mask sample, made safe. `!(v > 0.0f)` rather than `std::max` so a NaN
// lands on 0 -- the identical expression and the identical reason as
// `core::layerCoverage()`, which is the per-layer half of the same quantity.
inline float maskCoverageClamp(float v) noexcept {
  if (!(v > 0.0f)) return 0.0f;  // also catches NaN and every negative
  return v < 1.0f ? v : 1.0f;
}

// One 128x128 layer mask tile: a single half-float coverage per texel.
//
// The layout is the degenerate case of core::Tile's -- texel (x, y) at
// `[y*kTileSize + x]` -- with no interleaving to get wrong because there is
// one channel.
class MaskTile {
 public:
  // binary16 1.0. The only encoding of 1.0 there is, which is what makes the
  // "is this tile all reveal?" test in io/NpaintFile a word comparison rather
  // than a decode-and-compare. `--selftest` asserts it against
  // `floatToHalf(1.0f)` rather than trusting the literal.
  static constexpr uint16_t kRevealWord = 0x3C00;

  // Fills with 1.0 -- "reveal", the identity of the multiply a mask feeds, and
  // therefore the same thing an *unallocated* tile means. See this header on
  // why this is the one tile type in the codebase whose default is not zero.
  MaskTile() noexcept { texels_.fill(kRevealWord); }

  static constexpr int32_t kChannels = 1;
  static constexpr size_t kTexelCount =
      static_cast<size_t>(kTileSize) * static_cast<size_t>(kTileSize);

  // `local` must satisfy `0 <= local.x, local.y < kTileSize` -- exactly what
  // Tile.hpp's tileLocalOffset() produces from a document coordinate.
  // **Always returns a value in [0,1]**, whatever the stored word says.
  float readCoverage(PixelCoord local) const noexcept {
    return maskCoverageClamp(halfToFloat(texels_[texelIndex(local)]));
  }

  // Clamped on the way in as well as on the way out, so nothing this build
  // stores is ever out of range and the read clamp only ever has a *file's*
  // words to defend against.
  void writeCoverage(PixelCoord local, float v) noexcept {
    texels_[texelIndex(local)] = floatToHalf(maskCoverageClamp(v));
  }

  // Raw half-float storage, for io/NpaintFile's pack/unpack -- the same "HALF
  // in, HALF out, no conversion" path core::Tile and core::PigmentTile both
  // give their channels, so a mask round-trips a `.npaint` bit-identically.
  const uint16_t* data() const noexcept { return texels_.data(); }
  uint16_t* data() noexcept { return texels_.data(); }

  // True when every sample is exactly 1.0, i.e. when this tile is
  // indistinguishable from not existing. io/NpaintFile's drop rule; the
  // mirror of "every word is zero" for a content tile.
  bool isFullyRevealed() const noexcept {
    for (const uint16_t w : texels_) {
      if (w != kRevealWord) return false;
    }
    return true;
  }

 private:
  static size_t texelIndex(PixelCoord local) noexcept {
    return static_cast<size_t>(local.y) * static_cast<size_t>(kTileSize) +
           static_cast<size_t>(local.x);
  }

  std::array<uint16_t, kTexelCount> texels_{};
};

// Same discipline as core::Tile's and core::PigmentTile's own size assertions:
// a MaskTile is nothing but its texel buffer, so if this ever fails something
// grew the type by accident. 128*128*1*2 = 32768 = 32 KiB, a quarter of an
// RGBA tile and a seventh of a pigment tile.
static_assert(sizeof(MaskTile) == 32 * 1024,
              "one 128x128 single-channel f16 mask tile must be exactly 32 KiB -- a quarter "
              "of core::Tile's 128 KiB (core/Mask.hpp says why f16 and not uint8)");

// The sparse store a masked layer holds, from the same template `TileStore`
// and `PigmentTileStore` are aliases of. core/TileStore.hpp named this
// instantiation in advance ("Step 4's single-channel mask store is the next
// instantiation and needs nothing new here"), and it needed nothing new: the
// map's behaviour -- allocate on write, query without allocating, iterate only
// what exists -- is the same for a mask as for a tile of colour.
using MaskTileStore = TileStoreOf<MaskTile>;

// The coverage one mask tile gives at `local`, with `nullptr` meaning "no tile
// here" and therefore **1.0**.
//
// This is the leaf both readers of a mask go through -- core/Composite's walk,
// which hoists the tile lookup out of its texel loop, and
// `core::layerMaskCoverageAt()`, which does the lookup per call for the probe.
// One function, so a flattener and an eyedropper cannot disagree about a
// masked pixel any more than they can about a mixed one.
inline float maskCoverage(const MaskTile* tile, PixelCoord local) noexcept {
  return tile == nullptr ? 1.0f : tile->readCoverage(local);
}

}  // namespace np
