#pragma once
#include <array>
#include <cstdint>
#include <optional>

#include "core/Pigment.hpp"
#include "core/TileStore.hpp"

// core/SelectionMask (PLAN.md "Phase 7 -- Select and paste"; PRD E1, E2;
// DESIGN-imaging.md "Selections").
//
// This file was a bare `class SelectionMask {};` placeholder reserving a
// parameter slot so that honouring a selection would not become "the pervasive
// retrofit ADR-0001 warns about". The reservation worked -- `PaintSim`'s two
// deposit entry points already carry an unread `const SelectionMask*` -- and
// this is the real thing.
//
// --- The tile: one uint8 channel, 16 KiB ----------------------------------
//
// **Deliberately NOT the f16 that core/Mask.hpp chose for layer masks**, and
// that file already argued why the two differ: "a selection is transient,
// canvas-sized and regenerated by a tool. A layer mask is document data that
// must survive a save." A layer mask lives in the layer's own EXR part, where
// `io::NpaintRawPart` carries one `sampleTypeName` for every channel of that
// part, so an 8-bit mask on a HALF part would be quantised on every load and
// io/NpaintFile's "HALF in, HALF out, no conversion" claim would stop being
// true. A selection is under no such obligation.
//
// Checked against practice rather than assumed: Photoshop stores selections at
// **8 bits regardless of the document's bit depth** -- 256 degrees of
// selectability -- and weights every edit by that coverage. So r8unorm is the
// norm for this job, not a corner cut. 128*128*1 = 16 KiB per touched tile,
// half a layer mask tile and an eighth of an RGBA tile.
//
// PRD E2 ("selections store antialiased *coverage*, not a bitmask") is
// therefore satisfied with 256 levels, and PRD E8's distance-transform grow
// and shrink have somewhere to put a fractional radius's answer.
//
// --- Absent, empty and full are three different things --------------------
//
// core/Mask.hpp has a section under this name, and **the defaults here are the
// exact inverse of that one**. Getting this backwards does not produce a
// visibly wrong pixel; it produces an editor where either nothing can be
// painted or a selection does nothing, so it is stated at length.
//
//   **No selection** -- `Document::selection` is `std::nullopt`. There is no
//     selection, so *everything* is editable: `selectionCoverageAt()` returns
//     **1.0** everywhere and costs one null check. This is the state a
//     document spends almost all of its life in, and it must stay free.
//
//   **A selection with no tile at that coordinate** -- coverage **0.0**. The
//     texel is OUTSIDE the selection. This is the inverse of a layer mask,
//     where an absent tile means *reveal*. It is also why `SelectionTile`'s
//     zero-initialised default is already correct and needs no help, whereas
//     core/Mask.hpp had to reason about `getOrCreate()` handing back a tile of
//     1.0: unselected is zero, and zero is what a fresh tile holds.
//
//   **A selection that selects nothing** -- an engaged selection with zero
//     tiles. Not the same as no selection at all: every edit is refused
//     everywhere. `selectionSelectsNothing()` names it, because "why is
//     nothing happening" needs an answer a UI can say out loud.
//
// The asymmetry is not an accident of implementation. A layer mask answers
// "how much of this layer shows?", and a layer with no mask shows fully. A
// selection answers "how much of this edit lands here?", and the absence of a
// selection is not "select nothing", it is "no restriction". Those two
// absences genuinely mean opposite things.
namespace np {

// One 128x128 tile of selection coverage: a single uint8 per texel, where 0 is
// unselected and 255 is fully selected.
class SelectionTile {
 public:
  static constexpr size_t kTexelCount = static_cast<size_t>(kTileSize) * kTileSize;

  // Coverage at `local`, as 0.0..1.0. The divisor is 255, so 255 maps to
  // exactly 1.0 and a fully-selected texel is an exact identity in every
  // weighting below rather than 0.99609375 of one.
  float coverageAt(PixelCoord local) const noexcept {
    return static_cast<float>(texels_[texelIndex(local)]) * (1.0f / 255.0f);
  }

  // Quantises and stores. Values outside [0,1] are clamped rather than
  // wrapped: a grow/shrink or a boolean can land slightly outside, and an
  // unsigned wrap would turn "just over fully selected" into "unselected",
  // which is the worst possible rounding of that mistake.
  void writeCoverage(PixelCoord local, float coverage) noexcept {
    const float clamped = coverage < 0.0f ? 0.0f : (coverage > 1.0f ? 1.0f : coverage);
    // +0.5 then truncate: round-to-nearest, so 1.0 -> 255 and 0.5 -> 128.
    texels_[texelIndex(local)] = static_cast<uint8_t>(clamped * 255.0f + 0.5f);
  }

  const uint8_t* data() const noexcept { return texels_.data(); }
  uint8_t* data() noexcept { return texels_.data(); }

  // True when no texel is selected at all -- the drop rule, and the mirror of
  // core/Mask.hpp's `isFullyRevealed()`. A tile like this is indistinguishable
  // from not existing, so a constructor that produced one should not keep it.
  bool selectsNothing() const noexcept {
    for (const uint8_t v : texels_) {
      if (v != 0) return false;
    }
    return true;
  }

  // True when every texel is fully selected. The test a copy uses to decide it
  // can SHARE the source tile rather than weighting it texel by texel (PRD
  // M5), so this is the difference between a 4K copy costing a refcount and
  // costing 68 MB. Exact equality with 255, deliberately: 254 would weight
  // the tile by 0.996 and a shared tile would then be quietly wrong.
  bool selectsAll() const noexcept {
    for (const uint8_t v : texels_) {
      if (v != 255) return false;
    }
    return true;
  }

 private:
  static size_t texelIndex(PixelCoord local) noexcept {
    return static_cast<size_t>(local.y) * static_cast<size_t>(kTileSize) +
           static_cast<size_t>(local.x);
  }

  std::array<uint8_t, kTexelCount> texels_{};
};

// Same discipline as core::Tile, core::PigmentTile and core::MaskTile: the
// type is nothing but its texel buffer, so if this fails something grew it by
// accident. 128*128*1 = 16384 = 16 KiB.
static_assert(sizeof(SelectionTile) == 16 * 1024,
              "one 128x128 single-channel uint8 selection tile must be exactly 16 KiB -- half "
              "a MaskTile and an eighth of a core::Tile (this header says why uint8, not f16)");

// The sparse store, from the same template every other tile store is an alias
// of. Nothing new was needed here either: allocate on write, query without
// allocating, iterate only what exists.
using SelectionTileStore = TileStoreOf<SelectionTile>;

// The coverage one tile gives at `local`, with `nullptr` meaning "no tile
// here" and therefore **0.0** -- outside the selection.
//
// The leaf every reader goes through, so a deposit, an op and a clear cannot
// disagree about a partially-selected texel. Note the inverted default against
// core/Mask.hpp's `maskCoverage()`, whose nullptr means 1.0.
inline float selectionTileCoverage(const SelectionTile* tile, PixelCoord local) noexcept {
  return tile == nullptr ? 0.0f : tile->coverageAt(local);
}

// An active selection: coverage over the document, sparse by tile.
//
// A plain struct rather than a class with an invariant, matching how
// `MaskTileStore` sits inside `Layer`. The invariant that matters -- that
// no stored tile is entirely zero -- is a property of the constructors, not
// something enforced on every write, because a boolean or a quick-mask edit
// legitimately passes through states where it is false.
struct Selection {
  SelectionTileStore tiles;
};

// Coverage at a document-space texel, for a possibly-absent selection.
//
// **`nullptr` means 1.0**, and that is the whole reason this function exists
// rather than callers reaching into `Selection` themselves: the "no selection"
// case is the common one, it must mean "no restriction", and it must cost one
// branch. A caller that writes `sel ? sel->coverage(p) : 0.0f` has inverted
// the editor.
//
// **There are two readers of a selection, and only one of them is this.** A
// per-texel loop cannot afford a hash lookup per texel, so it hoists the tile
// out of the loop and calls `selectionTileCoverage()` directly, exactly as
// core/Composite does with `maskCoverage()` -- and then it owns the null-
// Selection branch itself. `clearThroughSelection()` below is the first such
// loop. So the "null means 1.0" rule is stated in two places, which is a real
// drift risk and is named here rather than discovered: a perturbation that
// inverted this function alone left the clear's own copy of the rule correct,
// and only one assertion failed. Any new hoisted loop must repeat the branch,
// and --selftest must assert the null case through that loop too.
float selectionCoverageAt(const Selection* selection, PixelCoord docTexel) noexcept;

// True when the selection exists but selects nothing anywhere. Distinct from
// no selection at all, and worth naming because it is the state behind "why is
// nothing happening when I paint".
bool selectionSelectsNothing(const Selection& selection) noexcept;

// --- Constructors ---------------------------------------------------------

// An antialiased rectangle in document texel space, with FRACTIONAL edges.
//
// The corners are real numbers, not integers, and a texel the edge crosses
// gets its true covered area rather than an in-or-out decision -- which is
// what makes this a coverage store rather than a bitmask (PRD E2). A texel
// spans [x, x+1) x [y, y+1), so its coverage is the area of the overlap
// between that unit square and the requested rectangle.
//
// Empty or inverted rectangles produce a selection with no tiles, which is
// `selectionSelectsNothing()` -- not an error, and not "select everything".
Selection selectRectangle(float x0, float y0, float x1, float y1);

// The tightest document-texel rectangle containing every selected texel, or
// `std::nullopt` when nothing is selected. `x1`/`y1` are exclusive, so an
// empty rectangle and a one-texel one are distinguishable.
//
// **Not for drawing the selection**, and that prediction is now settled rather
// than pending. This used to say that the bounds were "exact for a rectangular
// marquee and merely a bounding box for anything else -- so when lasso and wand
// land (PRD E3) and PRD E6's marching ants have to trace a real boundary, this
// is not the function that will do it". Those tools landed, the marching ants
// did draw this rectangle for a while, and every lasso, wand and Shift-added
// selection rendered as a box. **core/SelectionBoundary is the function that
// does it**, and the marching ants go through that.
//
// What this is still for is an EXTENT: the rectangle an op has to cover.
// ops/Gradient.hpp names it for a gradient's span and ops/Feather.cpp for the
// coarser tile-granular version of the same question. Nothing in this build
// calls it today -- the ants were its only caller -- which is stated rather
// than hidden, because a bounding box is exactly the right answer to "how much
// of the canvas does this op have to touch" and exactly the wrong answer to
// "where is the edge".
//
// O(selected tiles x texels), so a caller that needs it every frame should
// cache the answer on `selectionRevision` rather than calling it from a render
// loop -- `SelectionBoundaryCache` is the worked example.
struct SelectionBounds {
  int32_t x0 = 0, y0 = 0, x1 = 0, y1 = 0;
  int32_t width() const noexcept { return x1 - x0; }
  int32_t height() const noexcept { return y1 - y0; }
};
std::optional<SelectionBounds> selectionBounds(const Selection& selection);

// A selection covering the whole of a `width` x `height` document -- what
// Select All makes.
//
// Deliberately a real selection rather than `std::nullopt`, even though the
// two behave identically for every edit (both mean "no restriction"). The
// difference is that the user asked for one and must be able to see it: PRD
// E6's marching ants need a boundary to draw, and "Deselect" needs something
// to remove. So Select All and Deselect are distinguishable states that do the
// same thing to pixels, which is exactly how every editor behaves.
Selection selectAll(int32_t width, int32_t height);

// --- Editing through a selection ------------------------------------------

// PRD M1's clear: remove coverage-weighted paint, leaving premultiply-correct
// holes.
//
// The working space is **premultiplied** rgba16float (io/Export.hpp), and that
// is what makes a partial clear correct without any special care: scaling all
// four channels by `1 - coverage` is exactly "this texel is now `1-coverage`
// as present as it was". Doing the same to straight (unassociated) alpha would
// need RGB left alone and only alpha scaled, and mixing the two conventions up
// is the classic source of dark fringes around a feathered deletion.
//
// A null selection clears everything -- consistent with `selectionCoverageAt()`
// and with every editor: Select All is the default, so Delete with no marquee
// drawn empties the layer.
//
// Returns the number of texels whose value actually changed, so a caller can
// tell "cleared nothing because the selection was empty" from "cleared nothing
// because the layer already was".
size_t clearThroughSelection(TileStore& tiles, const Selection* selection);

// The Pigment-layer form, and **the weighting rule is a different shape**.
//
// core/Pigment.hpp stores a texel as a STRAIGHT latent plus a `mass` that is
// the alpha analogue; core/Composite projects the pair as
// `(latentToRgb(latent) * mass, mass)`. So clearing through coverage scales
// **mass alone and leaves the latent untouched** -- which is not an analogy
// but PRD F10's own rule for the eraser, stated there in those words.
//
// Scaling the latent as well, by reflex from the RGB path above, would drag
// the pigment's identity toward zero as it faded: a half-erased red would
// stop being red rather than becoming less of it. That is the pigment
// equivalent of the fringe the premultiplied path avoids, and it is why these
// are two functions rather than one template.
size_t clearThroughSelection(PigmentTileStore& tiles, const Selection* selection);

}  // namespace np
